version: 2.1

jobs:
  say-hello:
    docker:
      - image: cimg/base:stable
    steps:
      - checkout
      - run:
          name: "Say hello"
          command: "echo Hello, World!"

  # Define a new job for running tests
  run-tests:
    docker:
      - image: python:3.8  # Use an appropriate Python version
    steps:
      - checkout
      - run:
          name: "Install dependencies"
          command: "pip install -r requirements.txt"
      - run:
          name: "Run tests"
          command: "python -m unittest discover tests"

workflows:
  say-hello-workflow:
    jobs:
      - say-hello
      - run-tests  # Add the "run-tests" job to the workflow
