
# Sample Prometheus config
# This assumes that your Prometheus instance can access this application on localhost:8080

global:
  scrape_interval:     15s
  evaluation_interval: 15s

scrape_configs:
  - job_name: 'django-app'
    metrics_path: '/metrics'
    scrape_interval: 1s
    static_configs:
      - targets: ['192.168.100.3:8000'] # Replace with the IP and port of your Django application

  - job_name: 'other-app'
    metrics_path: '/metrics'
    scrape_interval: 15s
    static_configs:
      - targets: ['192.168.100.3:9182'] # Replace with the address where your other application is running
