global:
  scrape_interval: 15s

scrape_configs:
  - job_name: 'django-app'
    static_configs:
      - targets: ['app:8000']  # Replace 'app' with your service name and port as needed
    metrics_path: /metrics
    scheme: http
