apiVersion: apps/v1
kind: Deployment
metadata:
  name: web-app-testing
spec:
  replicas: 2
  selector:
    matchLabels:
      app: web-app-testing
  template:
    metadata:
      name: app
      labels:
        app: web-app-testing
    spec:
      containers:
        - name: app
          image: patronix9345/web-app:0.0.4
          ports:
            - containerPort: 8000
          livenessProbe:
            httpGet:
              path: /healthz
              port: 8000
            periodSeconds: 6
          readinessProbe:
            httpGet:
              path: /healthz
              port: 8000
            periodSeconds: 2
            initialDelaySeconds: 15
